// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/kynmh69/mormorare/internal/app"
	"github.com/kynmh69/mormorare/internal/database"
	"github.com/kynmh69/mormorare/internal/domain/repository"
	"github.com/kynmh69/mormorare/internal/handler"
)

// Injectors from wire_inject.go:

func InitializeEngine() *app.Engine {
	db := database.NewPostgres()
	userRepository := repository.NewUserRepository(db)
	userHandler := handler.NewUserHandler(userRepository)
	engine := app.NewEngine(db, userRepository, userHandler)
	return engine
}
