definitions:
  domain.ErrorJson:
    properties:
      error:
        type: string
    type: object
  handler.UserResponse:
    properties:
      birth_day:
        example: "2006-01-02"
        type: string
      email:
        example: example@test.com
        type: string
      user_name:
        example: test1
        type: string
    type: object
info:
  contact: {}
  title: Mormorare API
  version: "1.0"
paths:
  /api/v1/users:
    get:
      description: Retrieve all users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              items:
                $ref: '#/definitions/handler.UserResponse'
              type: array
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorJson'
      summary: Retrieve all users
      tags:
      - users
    post:
      consumes:
      - application/json
      description: Create a new user
      parameters:
      - description: set username
        in: body
        name: user_name
        required: true
        schema:
          type: string
      - description: set password
        in: body
        name: password
        required: true
        schema:
          type: string
      - description: set email
        in: body
        name: email
        required: true
        schema:
          type: string
      - description: set birthday
        in: body
        name: birthday
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handler.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorJson'
      summary: Create a new user
      tags:
      - users
  /api/v1/users/{user_name}:
    delete:
      description: Delete a user
      parameters:
      - description: set username
        in: path
        name: user_name
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorJson'
      summary: Delete a user
      tags:
      - users
swagger: "2.0"
