service:
  database:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
        POSTGRES_DB: app
        TZ: Asia/Tokyo
    networks:
      - app-network
    volumes:
        - database-data:/var/lib/postgresql/data
    restart: failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5
  users:
    image:
      context: .
      dockerfile: docker/users/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./go/src:/go/src/app
    env_file:
      - ./docker/users/.env
networks:
  app-network:
    driver: bridge
volume:
  database-data:
    driver: local