services:
  database:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
      TZ: Asia/Tokyo
    networks:
      - app-network
    volumes:
      - database-data:/var/lib/postgresql/data
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user" ]
      interval: 10s
      timeout: 5s
      retries: 5
  users:
    build:
      context: .
      dockerfile: ./docker/users/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./go/src:/go/src/app
    env_file:
      - ./docker/users/.env
networks:
  app-network:
    driver: bridge
volumes:
  database-data:
    driver: local